# Generated by Django 5.2 on 2025-05-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_aimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_models',
            field=models.ManyToManyField(blank=True, help_text='Kullanıcının favori modelleri', related_name='favorited_by', to='accounts.aimodel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='openrouter_api_key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
